# Numpy Basics

In [1]:
import numpy as np

In [5]:
a=np.array([1,2,3,4,5])
b=np.array([[5,6],[7,8],[9,10]])

In [7]:
print(a)
print(type(a))

print(a.shape)
print(b.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
(5,)
(3, 2)


In [9]:
c=np.array([[1],[2],[3],[4]])

In [10]:
print(c)
print(c.shape)


[[1]
 [2]
 [3]
 [4]]
(4, 1)


In [12]:
print(a[1])
print(c[2][0])

2
3


In [14]:
#create zero,ones,custom arrays
x=np.zeros((2,3))
y=np.ones((4,4))

print(x)
print(y)

z=np.full((3,3),5)
print(z)

#identity matrix
s=np.eye(4)
print(s)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[5 5 5]
 [5 5 5]
 [5 5 5]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
randomMatrix=np.random.random((2,3))
print(randomMatrix)

[[0.86797905 0.54703956 0.38191932]
 [0.6654319  0.22902805 0.14248247]]


In [18]:
print(randomMatrix[:,1])

[0.54703956 0.22902805]


In [20]:
randomMatrix[0:,-1]=5
print(randomMatrix)

[[0.86797905 0.54703956 5.        ]
 [0.6654319  0.22902805 5.        ]]


In [26]:
z=np.zeros((3,3),dtype='int64')
z[1,:]=5
z[:,-1]=7
print(z)

[[0 0 7]
 [5 5 7]
 [0 0 7]]


In [27]:
print(z.dtype)

int64


### Mathematical Operations

In [31]:
a=np.array([1,2,3,4])
b=np.array([5,6,7,8])

print(a+b)
print(np.add(a,b))

[ 6  8 10 12]
[ 6  8 10 12]


In [32]:
print(a-b)
print(np.subtract(a,b))

[-4 -4 -4 -4]
[-4 -4 -4 -4]


In [33]:
x=np.array([[1,2],[3,4]])
y=np.array([[5,6],[7,8]])

In [34]:
print(x*y)
print(np.multiply(x,y))

[[ 5 12]
 [21 32]]
[[ 5 12]
 [21 32]]


In [36]:
print(x/y)
print(np.divide(x,y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [37]:
print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [38]:
print(x)
print(y)

print(x.dot(y))
print(np.dot(x,y))

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[19 22]
 [43 50]]
[[19 22]
 [43 50]]


In [39]:
#dot product of two vectors is a scalar
print(a)
print(b)

print(a.dot(b))

[1 2 3 4]
[5 6 7 8]
70


In [42]:
print(a)
print(np.sum(a))

[1 2 3 4]
10


In [43]:
print(x)
print(np.sum(x))
print(np.sum(x,axis=0))
print(np.sum(x,axis=1))

[[1 2]
 [3 4]]
10
[4 6]
[3 7]


In [44]:
print(a)
print(b)

[1 2 3 4]
[5 6 7 8]


In [47]:
#stacking of arrays
np.stack((a,b),axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [50]:
t=np.stack((a,b),axis=1)
print(t)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [51]:
t.reshape((4,2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [52]:
t.reshape((2,-1))

array([[1, 5, 2, 6],
       [3, 7, 4, 8]])

In [54]:
t.reshape((-1,2))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

### Random Module of Numpy

In [71]:
a=np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [72]:
a=np.arange(10)+5
print(a)

[ 5  6  7  8  9 10 11 12 13 14]


In [73]:
np.random.seed(1)
np.random.shuffle(a)
print(a)

[ 7 14 11  9  5  8  6 12 13 10]


In [59]:
#random matrix
a=np.random.rand(2,3)
print(a)

[[0.98588105 0.74149386 0.6342714 ]
 [0.70927488 0.19139746 0.60664938]]


In [60]:
#generates numbers from standard normal distribution
a=np.random.randn(2,3)
print(a)

[[-0.53005742  0.23800996 -0.09067746]
 [-0.0438088  -0.72887964 -0.49331606]]


In [63]:
#random numbers from a range
a=np.random.randint(5,10,(3,2))
print(a)

[[6 6]
 [5 6]
 [6 9]]


In [64]:
a=np.random.randint(5,10,3)
print(a)

[7 6 9]


In [67]:
element=np.random.choice([5,2,78,69,420])
print(element)

420


### Statistics Functions

In [74]:
a=np.array([[1,2,3,4],[7,6,2,0]])

In [75]:
print(np.min(a))
print(np.min(a,axis=0))
print(np.min(a,axis=1))

0
[1 2 2 0]
[1 0]


In [76]:
print(np.max(a))
print(np.max(a,axis=0))
print(np.max(a,axis=1))

7
[7 6 3 4]
[4 7]


In [79]:
b=np.array([1,2,3,4,5])
m=sum(b)/5
print(m)
print(np.mean(b))
print(np.mean(a,axis=0))
print(np.mean(a,axis=1))

3.0
3.0
[4.  4.  2.5 2. ]
[2.5  3.75]


In [80]:
c=np.array([1,5,0,4,2])
print(np.median(c))

2.0


In [82]:
print(np.mean(c))
wts=np.array([1,2,3,4,5])

print(np.average(c,weights=wts))

2.4
2.466666666666667


In [83]:
#standard deviation and variance
u=np.mean(c)
mystd=np.sqrt(np.mean(abs(c-u)**2))
print(mystd)

dev=np.std(c)
print(dev)

1.8547236990991407
1.8547236990991407


In [84]:
variance=mystd**2
print(variance)
print(np.var(c))

3.44
3.44


In [85]:
#transpose of matrix
x=np.array([[1,2,3,4],[5,6,7,8]])
print(x)
xt=np.transpose(x)
print(xt)

[[1 2 3 4]
 [5 6 7 8]]
[[1 5]
 [2 6]
 [3 7]
 [4 8]]


In [88]:
y=np.array([1,2,3,4])
y=y.reshape((-1,1))
print(y)
print(np.transpose(y))

[[1]
 [2]
 [3]
 [4]]
[[1 2 3 4]]


### Broadcasting

In [89]:
l=np.array([1,2,3,4])
print(l)

l+=1
print(l)

l=np.sqrt(l)
print(l)

[1 2 3 4]
[2 3 4 5]
[1.41421356 1.73205081 2.         2.23606798]


In [91]:
l=np.array([[1,2,3,4],[5,6,7,8]])
print(l)

l+=1
print(l)

l=l**2
print(l)

[[1 2 3 4]
 [5 6 7 8]]
[[2 3 4 5]
 [6 7 8 9]]
[[ 4  9 16 25]
 [36 49 64 81]]


In [92]:
print(np.sqrt(l))

[[2. 3. 4. 5.]
 [6. 7. 8. 9.]]


### Matrix Multiplication

In [93]:
#normal matrix multiplication
x=np.array([[1,2,3],[4,5,6],[7,8,9]])
y=np.array([[3,5,7],[5,3,9],[9,8,4]])

print(x)
print(y)

print(x.shape)
print(y.shape)

prod=x.dot(y)
print(prod)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3 5 7]
 [5 3 9]
 [9 8 4]]
(3, 3)
(3, 3)
[[ 40  35  37]
 [ 91  83  97]
 [142 131 157]]


In [94]:
#element wise multiplication
x=np.array([[1,2,3],[4,5,6],[7,8,9]])

y=np.eye(3)
y=y*2
y+=1

print(x)
print(y)

print(x*y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[3. 1. 1.]
 [1. 3. 1.]
 [1. 1. 3.]]
[[ 3.  2.  3.]
 [ 4. 15.  6.]
 [ 7.  8. 27.]]


### Norms

In [96]:
x=np.array([-5,3,10])
lp2=np.linalg.norm(x)
print(lp2)

11.575836902790225


In [97]:
lp1=np.linalg.norm(x,ord=1)
print(lp1)

18.0


In [98]:
lpinf=np.linalg.norm(x,ord=np.inf)
print(lpinf)

10.0


In [1]:
import numpy as np

a=np.array([[1,-3,4],[-2,10,-7],[0,1,0],[0,0,0]])
b=np.array([[5,0],[-2,11],[-3,12]])

In [3]:
print(a)
print(b)
print(a.dot(b))

[[ 1 -3  4]
 [-2 10 -7]
 [ 0  1  0]
 [ 0  0  0]]
[[ 5  0]
 [-2 11]
 [-3 12]]
[[-1 15]
 [-9 26]
 [-2 11]
 [ 0  0]]


In [4]:
a=np.array([[2,-2,1],[-1,2,-1],[2,-4,1]])
lp1=np.linalg.norm(a,ord=2)
print(lp1)

5.9287221489704836


In [5]:
lpinf=np.linalg.norm(a,ord=np.inf)
print(lpinf)

7.0
