# Pandas Basics

In [1]:
import numpy as np
import pandas as pd

In [3]:
marks={
    "MarksA":np.random.randint(1,100,5),
    "MarksB":np.random.randint(1,100,5),
    "MarksC":np.random.randint(1,100,5)
}

In [15]:
df=pd.DataFrame(marks,dtype='float64')

In [16]:
print(df)

   MarksA  MarksB  MarksC
0    21.0    72.0    35.0
1    17.0    47.0    54.0
2    29.0    62.0    34.0
3    17.0    21.0    82.0
4    73.0     8.0    18.0


In [17]:
df.head(n=5)

MarksA  MarksB  MarksC
0    21.0    72.0    35.0
1    17.0    47.0    54.0
2    29.0    62.0    34.0
3    17.0    21.0    82.0
4    73.0     8.0    18.0

In [7]:
df.to_csv('marks.csv')

In [13]:
myData=pd.read_csv('marks.csv')
myData=myData.drop(columns='Unnamed: 0')
myData

MarksA  MarksB  MarksC
0      21      72      35
1      17      47      54
2      29      62      34
3      17      21      82
4      73       8      18

In [14]:
print(df.columns)

Index(['MarksA', 'MarksB', 'MarksC'], dtype='object')


In [18]:
myData.describe()

MarksA     MarksB     MarksC
count   5.000000   5.000000   5.000000
mean   31.400000  42.000000  44.600000
std    23.765521  27.027764  24.490815
min    17.000000   8.000000  18.000000
25%    17.000000  21.000000  34.000000
50%    21.000000  47.000000  35.000000
75%    29.000000  62.000000  54.000000
max    73.000000  72.000000  82.000000

In [19]:
df.tail(n=3)      #3 rows from the end

MarksA  MarksB  MarksC
2    29.0    62.0    34.0
3    17.0    21.0    82.0
4    73.0     8.0    18.0

In [20]:
df.iloc[3]

MarksA    17.0
MarksB    21.0
MarksC    82.0
Name: 3, dtype: float64

In [21]:
df.iloc[3,1]

21.0

In [22]:
df.iloc[3][1]

21.0

In [24]:
idx=df.columns.get_loc('MarksB')
df.iloc[4][idx]

8.0

In [25]:
idx=[df.columns.get_loc('MarksB'),df.columns.get_loc('MarksC')]
df.iloc[3][idx]

MarksB    21.0
MarksC    82.0
Name: 3, dtype: float64

In [30]:
df.iloc[:3,idx]

MarksB  MarksC
0    72.0    35.0
1    47.0    54.0
2    62.0    34.0

In [31]:
df.iloc[:3,[1,2]]

MarksB  MarksC
0    72.0    35.0
1    47.0    54.0
2    62.0    34.0

In [35]:
#sorting
myData.sort_values(["MarksC","MarksA"],ascending=False)

MarksA  MarksB  MarksC
3      17      21      82
1      17      47      54
0      21      72      35
2      29      62      34
4      73       8      18

In [36]:
data_array=myData.values

In [37]:
print(data_array)
print(data_array.shape)

[[21 72 35]
 [17 47 54]
 [29 62 34]
 [17 21 82]
 [73  8 18]]
(5, 3)


In [38]:
print(type(data_array))

<class 'numpy.ndarray'>


In [42]:
new_df=pd.DataFrame(data_array,columns=["physics","chemistry","maths"])

In [43]:
new_df

physics  chemistry  maths
0       21         72     35
1       17         47     54
2       29         62     34
3       17         21     82
4       73          8     18

In [44]:
phy=new_df.get("physics")
print(phy)

0    21
1    17
2    29
3    17
4    73
Name: physics, dtype: int64


In [45]:
type(phy)

pandas.core.series.Series

In [46]:
phy=list(new_df.get("physics"))
print(type(phy))

<class 'list'>
